name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Build Binary
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build -o dist/maplepie.exe ./cmd/maple-pie-server
          GOOS=linux GOARCH=amd64 go build -o dist/maplepie-linux ./cmd/maple-pie-server
          GOOS=darwin GOARCH=amd64 go build -o dist/maplepie-macos ./cmd/maple-pie-server

      - name: Prepare ZIP
        run: |
          cp scripts/launch_me.bat dist/
          cp scripts/launch_me.sh dist/

          cd dist
          zip maplepie-windows.zip maplepie.exe launch_me.bat
          zip maplepie-linux.zip maplepie-linux launch_me.sh
          zip maplepie-macos.zip maplepie-macos launch_me.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maplepie-binaries
          path: dist/*.zip

  release:
    name: Version, Tag, Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maplepie-binaries
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
