name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: bump-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maplepie-binaries
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
