name: Testing

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1
        continue-on-error: true # ⚠️ allows linter to fail without failing the job
