name: Auto Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: Bump Version and Tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        uses: phips28/gh-action-bump-version@v11
        with:
          tag-prefix: "v"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
