name: Auto Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: Bump Version and Tag
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          release_branches: main
